package org.syswin.fences.models.enums;

public enum EventType {
    CREATED_OBJECTIVE, DELETED_OBJECTIVE, ADDED_FENCE_TO_OBJECTIVE, DELETED_FENCE_FROM_OBJECTIVE, ADDED_FENCE, DELETED_FENCE, STOLEN_FENCE, FOUND_FENCE, CANCELED_ALERT;
}
